CUDA_VISIBLE_DEVICES=3 python src/train.py \
    task_name=finetune_method1_FSD50k \
    experiment=finetune_method1 \
    data=FSD50K_weight \
    +n_q=1 \
    +nq_rank=0 \
    +mask_prob=0.0 \
    +is_mixup=False \
    +train_mode=mlc \
    +audio_time=10.0 \
    model.lr=0.00001 \
    +is_finetune=True \
    +model_config=../model_config \
    +pretrain_model_pt=/home/lizhaohui/ATT/AudioFormer/data/nq0_53.9.pt \
    data.batch_size=16 \
    logger=tensorboard \
    callbacks.early_stopping.monitor=val/mAP \
    callbacks.model_checkpoint.monitor=val/mAP \
    trainer=gpu \
    trainer.devices=1 \
    trainer.precision=32 \
    trainer.max_epochs=10 \
    paths.root_dir=/home/lizhaohui/ATT/AudioFormer \
    paths.data_dir=/media/data1/lizhaohui/ATT/data/FSD50K/ground_truth \
    +trainer.val_check_interval=1.0 \
    callbacks.early_stopping.patience=3 
